# Generated by Django 5.2.4 on 2025-08-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddredd',
            new_name='ShippingAddress',
        ),
    ]
