# Generated by Django 5.2.4 on 2025-08-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='compelete',
            new_name='complete',
        ),
    ]
